apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-yyfm
  namespace: sbudhwar-1
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: my-application
        appstudio.openshift.io/component: devfile-sample-yyfm
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-yyfm-
      labels:
        appstudio.openshift.io/application: my-application
        appstudio.openshift.io/component: devfile-sample-yyfm
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: sbudhwar-1
    spec:
      params:
      - name: git-url
        value: https://github.com/sclorg/nodejs-ex
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:sbudhwar-1-devfile-sample-yyfm-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/nodeshift-starters/devfile-sample/main/Dockerfile
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
