apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yyfm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yyfm
    app.kubernetes.io/part-of: my-application
  name: devfile-sample-yyfm
  namespace: sbudhwar-1
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-sample-yyfm
    weight: 100
status: {}
